# .github/workflows/deploy.yml
name: Reusable Deployment Workflow

on:
  workflow_call:
    inputs:
      target_host:
        required: true
        type: string
      folders:
        required: true
        type: string
      run_test:
        required: false
        default: 'false'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Deploy to target host
      run: |
        for folder in ${{ inputs.folders }}; do
          echo "Deploying $folder to host: ${{ inputs.target_host }}"
          # Here you would run your actual deployment command using the target host
          # For example:
          gh workflow run .github/workflows/deploy-folder.yml \
            -f folder=$folder \
            -f target_host="${{ inputs.target_host }}"
        done

    - name: Check for run test annotation
      id: test_annotation
      run: |
        pr_body="${{ github.event.pull_request.body }}"
        echo "PR Body: $pr_body"
        
        # Extract command if #run-test annotation is found
        if echo "$pr_body" | grep -q "#run-test"; then
          echo "Run test annotation found."
          # Extract the command
          command=$(echo "$pr_body" | grep -oP '#run-test \K.*')
          echo "command=$command" >> $GITHUB_ENV
          echo "run_test=true" >> $GITHUB_ENV
        else
          echo "Run test annotation not found."
          echo "Example of annotation to execute the test: '#run-test python3 script.py --branch main_ --autobuild PRECHECKIN --culprit_change 49153210 --fix_change 49165301 --build_breakage yes'."
          echo "run_test=false" >> $GITHUB_ENV

    - name: Run tests if annotation is present
      if: env.run_test == 'true'
      run: |
        echo "Running remote host tests with command:"
        echo "${{ env.command }}"

        # Set -e ensures the script exits on any command failure
        set -e

        # Execute the command and capture the exit status
        eval "${{ env.command }}"
        
        # Check if the script failed
        if [ $? -ne 0 ]; then
          echo "Test execution failed. Exiting..."
          exit 1
        fi

        echo "Test execution completed successfully."
