name: Zabbix Script Deployment

on:
  pull_request:
    branches:
      - master

jobs:
  detect-changes:
    name: Detect Changed Folders
    runs-on: ubuntu-latest

    steps:
    - name: Check PR Description for WorkItem
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        if [[ ! "${{ github.event.pull_request.body }}" =~ @W-[0-9]{8} ]]; then
          echo "PR description must include a WorkItem annotation in the format '@W-12345678'."
          exit 1
        fi

    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Get list of changed files
      id: changes
      run: |
        # Get list of changed files and extract the unique folders
        changed_files=$(git diff --name-only origin/master ${{ github.sha }})
        changed_folders=$(echo "$changed_files" | grep '/' | cut -d '/' -f1 | sort -u)
        echo "Changed folders: $changed_folders"
        echo "::set-output name=folders::$changed_folders"

    - name: Check for run test annotation
      id: test_annotation
      run: |
        pr_body="${{ github.event.pull_request.body }}"
        echo "PR Body: $pr_body"
        
        # Extract command if #run-test annotation is found
        if echo "$pr_body" | grep -q "#run-test"; then
          echo "Run test annotation found."
          # Extract the command
          command=$(echo "$pr_body" | grep -oP '#run-test \K.*')
          echo "command=$command" >> $GITHUB_ENV
          echo "run_test=true" >> $GITHUB_ENV
        else
          echo "Run test annotation not found."
          echo "Example of annotation to execute the test: '#run-test python3 script.py --branch main_ --autobuild PRECHECKIN --culprit_change 49153210 --fix_change 49165301 --build_breakage yes'."
          echo "run_test=false" >> $GITHUB_ENV
        fi

    - name: Deploy changed folders
      run: |
        for folder in ${{ steps.changes.outputs.folders }}; do
          echo "Triggering deployment for $folder"
          gh workflow run .github/workflows/deploy-folder.yml \
            -f folder=$folder \
            -f target_host="ops-zbx-prxy-3-test-gcp.eng.sfdc.net"
        done

    - name: Run tests if annotation is present
      if: env.run_test == 'true'
      run: |
        echo "Running remote host tests with command:"
        echo "${{ env.command }}"

        # Set -e ensures the script exits on any command failure
        set -e

        # Execute the command and capture the exit status
        eval "${{ env.command }}"
        
        # Check if the script failed
        if [ $? -ne 0 ]; then
          echo "Test execution failed. Exiting..."
          exit 1
        fi

        echo "Test execution completed successfully."
