name: Zabbix Script Deployment

on:
  push:
    branches:
      - '**'  # Trigger on all branches to validate and deploy on any branch commit
  pull_request:
    types:
      - closed  # For prod deployment on merge

jobs:
  detect-changes:
    name: Detect Changed Folders
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    # This step will run on both push (for all branches) and pull_request
    - name: Check PR Description for WorkItem (only on push to master or PRs)
      if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'pull_request' }}
      run: |
        if [[ ! "${{ github.event.pull_request.body }}" =~ @W-[0-9]{8} ]]; then
          echo "PR description must include a WorkItem annotation in the format '@W-12345678'."
          exit 1
        else
          echo "${{ github.event.pull_request.body }}" 
          echo "${{ github.event.pull_request.title }}" 
        fi

    - name: Get list of changed files
      id: changes
      run: |
        # Get list of changed files and extract the unique folders
        changed_files=$(git diff --name-only origin/main ${{ github.sha }})
        changed_folders=$(echo "$changed_files" | grep '/' | cut -d '/' -f1 | sort -u)
        echo "Changed folders: $changed_folders"
        echo "::set-output name=folders::$changed_folders"

  # Deploy to the test environment on all branch commits
  deploy-to-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    needs: detect-changes
    if: github.ref != 'refs/heads/main'  # Only deploy to test on non-master branches

    steps:
    - name: Call reusable workflow for test environment
      uses: ./.github/workflows/deploy.yml
      with:
        target_host: "ops-zbx-prxy-3-test-gcp.eng.sfdc.net"
        folders: ${{ steps.changes.outputs.folders }}
        run_test: 'true'  # Assuming you want to run tests on commit

  # Deploy to production environment on PR merge to master
  deploy-to-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: detect-changes
    if: github.event.pull_request.merged == true

    steps:
    - name: Call reusable workflow for production environment
      uses: ./.github/workflows/deploy.yml
      with:
        target_host: "ops-zbx-prxy-3-gcp.eng.sfdc.net"
        folders: ${{ steps.changes.outputs.folders }}
        run_test: 'false'  # No tests required for production deployment
